# configuration file for the shared solar messaging parser 

log: switchboard.logger

classifers:
  - name: consumer-message-numeric
    classifer: ^[0-9]
    parser: parse_consumer

  - name: consummer-message-alphabetical
    classifer: ^[A-Za-z]
    parser: parse_consumer
    
  - name: meter-message-compressed
    classifer: ^\(l.*\)$
    parser: parse_meter_compressed

  - name: meter-message-pcu
    classifer: ^\(pcu*
    parser: parse_meter_pcu

  - name: meter-message-uncompressed
    classifer: ^\(.*\)$
    parser: parse_meter

routes:
  - name: check_circuit_balance
    matchers: [^(bal).(\w+), ^(solde).(\w+), ^(2).(\w+)]

  - name: add_credit
    matchers: [ ^(add).(\w+).(\d+), ^(recharge).(\w+).(\d+), ^(9).(\w+).(\w+)]

  - name: turn_on
    matchers: [^(on).(\w+), ^(1).(\w+)]

  - name: turn_off
    matchers: [^(off).(\w+), ^(0).(\w+)]

  - name: set_primary_phone
    matchers: [^(prim).(\w+), ^(tel).(\w+), ^(4).(\w+)]

  - name: get_user_history
    matchers: [^(use).(\w+), ^(3).(\w+)]


message-relays:
  - name: MaliTel-Mali
    country: Mali
    relay-number: 22364614444
    type: Kannel
  - name: Airtel-Uganda
    country: Uganda
    relay-number: +256753444466
    host: 41.223.84.25
    
